export const rawData = `Position	Name	Total
RB	Saquon Barkley RB | PHI	196
RB	Jahmyr Gibbs RB | DET	188
RB	Derrick Henry RB | BAL	171
RB	James Cook RB | BUF	145
RB	Bijan Robinson RB | ATL	145
RB	Josh Jacobs RB | GB	135
RB	Jonathan Taylor RB | IND	125
RB	Kyren Williams RB | LAR	123
RB	De'Von Achane RB | MIA	115
RB	Joe Mixon RB | HOU	108
RB	James Conner RB | ARI	100
RB	Chase Brown RB | CIN	99
RB	Bucky Irving RB | TB	98
RB	Chuba Hubbard RB | CAR	97
RB	Alvin Kamara RB | NO	96
RB	Aaron Jones RB | MIN	95
RB	David Montgomery RB | DET	90
RB	Breece Hall RB | NYJ	90
RB	J.K. Dobbins RB | DEN	79
RB	D'Andre Swift RB | CHI	78
RB	Najee Harris RB | LAC	74
RB	Rachaad White RB | TB	71
RB	Kenneth Walker III RB | SEA	70
RB	Zach Charbonnet RB | SEA	70
RB	Rhamondre Stevenson RB | NE	70
RB	Tony Pollard RB | TEN	69
RB	Brian Robinson Jr. RB | WAS	66
RB	Rico Dowdle RB | CAR	63
RB	Kareem Hunt RB | KC	60
RB	Tyrone Tracy Jr. RB | NYG	59
RB	Tank Bigsby RB | JAC	54
RB	Jordan Mason RB | MIN	48
RB	Javonte Williams RB | DAL	43
RB	Ray Davis RB | BUF	42
RB	Isaac Guerendo RB | SF	40
RB	Austin Ekeler RB | WAS	35
RB	Ameer Abdullah RB | SF	34
RB	Tyjae Spears RB | TEN	34
RB	Jerome Ford RB | CLE	32
RB	Justice Hill RB | BAL	31
RB	Dameon Pierce RB | HOU	30
RB	Emanuel Wilson RB | GB	29
RB	Alexander Mattison RB | MIA	28
RB	Ty Johnson RB | BUF	27
RB	Tyler Allgeier RB | ATL	25
RB	Devin Singletary RB | NYG	24
RB	Cam Akers RB | NO	24
RB	Roschon Johnson RB | CHI	24
RB	Sean Tucker RB | TB	22
RB	Jeremy McNichols RB | WAS	22
RB	Braelon Allen RB | NYJ	21
RB	Jaleel McLaughlin RB | DEN	21
RB	Zack Moss RB | CIN	20
RB	Travis Etienne RB | JAC	19
RB	Miles Sanders RB | DAL	19
RB	Gus Edwards RB | LAC	16
RB	Nick Chubb RB | HOU	16
RB	Jaylen Warren RB | PIT	16
RB	Raheem Mostert RB | LV	15
RB	Antonio Gibson RB | NE	15
RB	Kyle Juszczyk RB | SF	15
RB	Emari Demercado RB | ARI	13
RB	Hassan Haskins RB | LAC	13
RB	Isiah Pacheco RB | KC	13
RB	Chris Rodriguez Jr. RB | WAS	13
RB	Isaiah Davis RB | NYJ	11
RB	Ezekiel Elliott RB | LAC	11
RB	Patrick Ricard RB | BAL	10
RB	Tyler Goodson RB | IND	10
RB	Samaje Perine RB | CIN	9
RB	Patrick Taylor RB | SF	9
RB	Dare Ogunbowale RB | HOU	9
RB	Tony Jones RB | ARI	9
RB	Christian McCaffrey RB | SF	9
RB	Michael Burton RB | DEN	9
RB	Michael Carter RB | ARI	8
RB	Trey Sermon RB | PIT	8
RB	Trey Benson RB | ARI	8
RB	Khalil Herbert RB | IND	8
RB	Audric Estime RB | DEN	7
RB	Kenneth Gainwell RB | PIT	6
RB	Kimani Vidal RB | LAC	6
RB	Jamaal Williams RB | NO	6
RB	JaMycal Hasty RB | NE	6
RB	Cordarrelle Patterson RB | PIT	5
RB	DeeJay Dallas RB | ARI	5
RB	Kendre Miller RB | NO	5
RB	Christopher Brooks RB | GB	4
RB	Sincere McCormick RB | LV	4
RB	Ronnie Rivers RB | LAR	4
RB	Ty Chandler RB | MIN	4
RB	Pierre Strong Jr. RB | CLE	4
RB	C.J. Ham RB | MIN	3
RB	Jaylen Wright RB | MIA	3
RB	Alec Ingold RB | MIA	3
RB	Zamir White RB | LV	2
RB	Boston Scott RB | PIT	0
WR	Ja'Marr Chase WR | CIN	167
WR	Justin Jefferson WR | MIN	117
WR	Brian Thomas Jr. WR | JAC	112
WR	Terry McLaurin WR | WAS	102
WR	Amon-Ra St. Brown WR | DET	100
WR	Jameson Williams WR | DET	89
WR	Mike Evans WR | TB	85
WR	Tee Higgins WR | CIN	83
WR	CeeDee Lamb WR | DAL	80
WR	A.J. Brown WR | PHI	78
WR	Drake London WR | ATL	78
WR	DeVonta Smith WR | PHI	77
WR	Courtland Sutton WR | DEN	76
WR	Jordan Addison WR | MIN	74
WR	Malik Nabers WR | NYG	73
WR	Jaxon Smith-Njigba WR | SEA	73
WR	Nico Collins WR | HOU	73
WR	Ladd McConkey WR | LAC	73
WR	Davante Adams WR | LAR	72
WR	Rashod Bateman WR | BAL	68
WR	Jayden Reed WR | GB	68
WR	Xavier Worthy WR | KC	64
WR	Alec Pierce WR | IND	64
WR	Jerry Jeudy WR | CLE	64
WR	Darnell Mooney WR | ATL	62
WR	Garrett Wilson WR | NYJ	62
WR	Marvin Harrison Jr. WR | ARI	61
WR	Quentin Johnston WR | LAC	60
WR	Puka Nacua WR | LAR	59
WR	Jauan Jennings WR | SF	57
WR	Calvin Ridley WR | TEN	57
WR	Tyreek Hill WR | MIA	57
WR	Cooper Kupp WR | SEA	57
WR	Jalen McMillan WR | TB	56
WR	Nick Westbrook-Ikhine WR | MIA	55
WR	Zay Flowers WR | BAL	54
WR	DJ Moore WR | CHI	54
WR	Keenan Allen WR | LAC	53
WR	DK Metcalf WR | PIT	50
WR	Jalen Tolbert WR | DAL	50
WR	Deebo Samuel WR | WAS	48
WR	Josh Downs WR | IND	47
WR	Marvin Mims WR | DEN	47
WR	Allen Lazard WR | NYJ	45
WR	Chris Godwin WR | TB	44
WR	Adam Thielen WR | CAR	44
WR	Jakobi Meyers WR | LV	43
WR	Stefon Diggs WR | NE	42
WR	Demarcus Robinson WR | SF	42
WR	Jalen Nailor WR | MIN	40
WR	George Pickens WR | DAL	39
WR	Marquez Valdes-Scantling WR | SEA	34
WR	DeAndre Hopkins WR | BAL	34
WR	Khalil Shakir WR | BUF	34
WR	Rashid Shaheed WR | NO	33
WR	Calvin Austin III WR | PIT	32
WR	Keon Coleman WR | BUF	32
WR	Dontayvion Wicks WR | GB	32
WR	Amari Cooper WR | BUF	31
WR	Cedric Tillman WR | CLE	31
WR	Andrei Iosivas WR | CIN	31
WR	Kayshon Boutte WR | NE	31
WR	Mack Hollins WR | NE	31
WR	Diontae Johnson WR | CLE	30
WR	Romeo Doubs WR | GB	30
WR	Jaylen Waddle WR | MIA	30
WR	Tre Tucker WR | LV	30
WR	Rome Odunze WR | CHI	29
WR	Michael Pittman WR | IND	29
WR	Ricky Pearsall WR | SF	27
WR	Rashee Rice WR | KC	27
WR	Jalen Coker WR | CAR	26
WR	Tank Dell WR | HOU	26
WR	Michael Wilson WR | ARI	26
WR	Christian Watson WR | GB	25
WR	Demario Douglas WR | NE	25
WR	Olamide Zaccheaus WR | CHI	24
WR	Xavier Legette WR | CAR	24
WR	Devaughn Vele WR | DEN	23
WR	Parker Washington WR | JAC	23
WR	Chris Olave WR | NO	22
WR	Darius Slayton WR | NYG	22
WR	David Moore WR | CAR	20
WR	Tyler Lockett WR | TEN	19
WR	Tim Patrick WR | DET	18
WR	JuJu Smith-Schuster WR | KC	17
WR	KaVontae Turpin WR | DAL	16
WR	Brandin Cooks WR | NO	16
WR	Wan'Dale Robinson WR | NYG	15
WR	Greg Dortch WR | ARI	15
WR	Elijah Moore WR | BUF	15
WR	Josh Palmer WR | BUF	14
WR	Ray-Ray McCloud WR | ATL	13
WR	Christian Kirk WR | HOU	13
WR	Tylan Wallace WR | BAL	12
WR	DJ Turner WR | LV	12
WR	Derius Davis WR | LAC	12`;
